Runbook for handling uptime alerts
vshn/application-catalog-docs pull request #116
Opened 2024-09-25 09:11 UTC by wejdross

## Summary

## Checklist

- [ ] Try to isolate changes into separate PRs (to build a better changelog).
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues if applicable.

2024-09-25 10:45 UTC, Kidswiss requested changes

2024-09-25 10:45 UTC, Kidswiss commented on docs/modules/ROOT/pages/how-tos/appcat/GuaranteedUptimeTarget.adoc
> +.Check logs of our comp-functions
I doubt this is helpful to anyone who's never worked with our AppCat.
Also the comp-functions don't necessarily say anything about why a specific service is not working.

2024-09-25 10:45 UTC, Kidswiss commented on docs/modules/ROOT/pages/how-tos/appcat/GuaranteedUptimeTarget.adoc
> +For stuck resources, You can create dummy label on object and then rollout restart crossplane function-appcat and provider-kubernetes.
Someone who has never used Crossplane might not know what a "stuck" resource is.

2024-09-26 12:00 UTC, Kidswiss approved these changes
Just one more nit, rest LGTM

2024-09-27 06:36 UTC, wejdross commented on docs/modules/ROOT/pages/how-tos/appcat/GuaranteedUptimeTarget.adoc
> +kubectl --as cluster-admin get xvshn[TAB here for specific service] | egrep $instanceNamespace_generated_chars # also describe to read what happened
I changed to that and also added a real life example, so it's going to be easier for engineers to go through our abstractions

2024-09-27 06:40 UTC, Kidswiss commented on docs/modules/ROOT/pages/how-tos/appcat/GuaranteedUptimeTarget.adoc
> +kubectl --as cluster-admin get xvshn[TAB here for specific service] | egrep $instanceNamespace_generated_chars # also describe to read what happened
I still shows as `kubectl --as cluster-admin get xvshn` for me not `kubectl --as cluster-admin describe xvshn`

2024-09-27 10:49 UTC, merged