Document implementation of new service
vshn/application-catalog-docs pull request #6
Opened 2021-04-13 15:25 UTC by srueg

Relates to APPCAT-34

2021-04-14 09:30 UTC, ccremer requested changes

2021-04-14 09:30 UTC, ccremer commented on docs/modules/ROOT/pages/explanations/crossplane_service_broker.adoc
> +* `service.syn.tools/updatable`: If the service instances can be updated
```suggestion
* `service.syn.tools/updatable`: Whether the service instances can be updated
```

2021-04-14 09:30 UTC, ccremer commented on docs/modules/ROOT/pages/explanations/crossplane_service_broker.adoc
> +* `service.syn.tools/updatable`: If the service instances can be updated
```suggestion
* `service.syn.tools/updatable`: Whether the service instances can be updated
```

2021-04-14 09:30 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/implement_new_service_offering.adoc
> +    service.syn.tools/id: 6ca63cdb-0cfa-4c5e-b080-72f22ff5f3e6
```suggestion
    service.syn.tools/id: 6ca63cdb-0cfa-4c5e-b080-72f22ff5f3e6 # This is the ID from 'compositefooinstances.syn.tools' above
```

2021-04-14 09:30 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/implement_new_service_offering.adoc
> +Especially to define multiple plans this approach helps to keep the config more DRY and maintainable.
```suggestion
This approach especially helps in defining multiple plans in order to keep the config more DRY and maintainable.
```

2021-04-14 09:30 UTC, ccremer commented on docs/modules/ROOT/pages/how-tos/implement_new_service_offering.adoc
> +This example setup will generate the same Crossplane resoruces as showcased in the previous examples.
```suggestion
This example setup will generate the same Crossplane resources as showcased in the previous examples.
```

2021-04-14 11:29 UTC, ccremer approved these changes

2021-04-15 06:21 UTC, tobru approved these changes

2021-04-15 07:44 UTC, merged